### ISSUE TITLE
Option to reset preferences

### ISSUE THREAD

**Issue by mDroidd** [Pixplicity/gene-rate#1]
It'd be usefull (for testing purposes) to have a call that resets the entire preferences to simulate user behavior in an isolated environment. The test() function is useful, but it always shows the snackbar/dialog.

Thanks in advance. Great project!

**Comment by mDroidd** [comment]
A proposed implementation is included in #2 .

**Comment by mlagerberg** [comment]
Thanks! Merged, will be in the next release. I've modified it a bit by putting the `reset` method in `Rate` rather than `Builder`, where it makes more sense.
