### ISSUE TITLE
Light theme support

### ISSUE THREAD

**Issue by soenkegissel** [Pixplicity/gene-rate#10]
Currently only dark theme is supported. On light apps this sometimes doesn't look very nice.
Can a light theme be applied during build?

**Comment by mlagerberg** [comment]
Unfortunately I haven't been able to add support for a custom theme (due to Android not supporting setting the theme programmatically) so I've added basic light and dark theme support in version 1.3.0.
Simply activate the light version using `.setLightTheme(true)`.

**Comment by soenkegissel** [comment]
That is more than I can expect. Thank you very much!

**Comment by mlagerberg** [comment]
And it only took eight months! :) Enjoy
