### ISSUE TITLE
On emulator canRateApp() returns false

### ISSUE THREAD

**Issue by soenkegissel** [Pixplicity/gene-rate#11]
I am testing on an emulator and it took me a while to figure out canRateApp() is returning false, so a request is never shown.
You can check if the device is an emulator and return accordingly.

**Comment by kassim** [comment]
I think if you use one of the emulators that have Google Play Store on you should be able to test it

<img width="630" alt="screen shot 2018-02-23 at 10 11 45" src="https://user-images.githubusercontent.com/11020264/36586407-f1f2d404-1881-11e8-8f48-3a5034ab78f5.png">

**Comment by soenkegissel** [comment]
The canOpenIntent(Intent) can return 0 if the emulator has no app to open Intent.ACTION_VIEW.
I checked showRequest() what the return of canRateApp() is - it is sometimes false on emulator.

**Comment by kassim** [comment]
yeah it'd be false if there's no Google Play Store app installed, hence why I recommend you using one of the emulators that do have it installed

**Comment by soenkegissel** [comment]
Hmm. I have to admit I could have tested it on a device with no PlayStore
installed.
Thank you very much.

kassim <notifications@github.com> schrieb am Fr., 23. Feb. 2018 um
14:42 Uhr:
