### ISSUE TITLE
Resolving some symbloes problem

### ISSUE THREAD

**Issue by echopros** [Pixplicity/gene-rate#17]
hi. could you please help ? 

cannot resolve those symboles after inserting code in OnCreate() method: "context"  "OnFeedBackListener"  "Toast"  "root"  "rating_message"

thanks in advance
![capture](https://user-images.githubusercontent.com/24847389/40275806-8d98a85c-5be9-11e8-905e-c8721509f665.JPG)

**Comment by mlagerberg** [comment]
`import com.pixplicity.generate.OnFeedbackListener;` will fix the first one. The others are either symbols from your own code or symbols that should be replaced by your own code, so I will leave that up to you.
