### ISSUE TITLE
BUG: It's causing Proguard not to obfuscate classes

### ISSUE THREAD

**Issue by Xoshbin** [Pixplicity/gene-rate#21]
It's been exactly 23 hours that I'm looking why Proguard not obfuscating my classes and finally after removing this library from dependencies it's been working again. this library is great and I loved it but didn't publish it with my app yet because it was blocking Proguard to obfuscate. So please fix this bug.

**Comment by pflammertsma** [comment]
Oh yeah, this isn't good! It appears the proguard rules are far too generic; see:
https://github.com/Pixplicity/gene-rate/blob/e6194b1cd14c917cb273b8a9d917352f0d56888b/library/consumer-proguard-rules.pro#L5
