### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by m-i-n-a-r** [Pixplicity/gene-rate#32]
I'm using the dependency in the readme, but when i do and try to compile my app, i get
  ```> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
     > Could not find :unspecified:.
       Required by:
           project :app > com.pixplicity.generate:gene-rate:1.3.0
```

I guess it's not a problem on my side, since i used the library successfully before

**Comment by pflammertsma** [comment]
Have you perhaps removed jCenter from your repositories? I don't believe Gene-rate is available on Maven Central yet.

**Comment by m-i-n-a-r** [comment]
Well, yes I did. 😅 It's about to be discontinued as you know, and I assumed that Gene-rate was already available on Maven Central. Any ETA on this?

**Comment by m-i-n-a-r** [comment]
Still broken, i removed the library from my app for now. Technically the issue is still there, but i'm going to close it until someone else face this issue.
