### ISSUE TITLE
Checkbox unchecked color

### ISSUE THREAD

**Issue by mDroidd** [Pixplicity/gene-rate#6]
I noticed that the checkbox is colored dark in a similar color that the snackbar has when it's unchecked (making it nearly unvisible). According to [Material Design](https://material.io/guidelines/components/selection-controls.html#), it has to colored light on a dark background.

I checked out the [in_snackbar.xml layout file](https://github.com/Pixplicity/gene-rate/blob/develop/library/src/main/res/layout/in_snackbar.xml) and noticed a lot of attributes like `?android:attr/textColorSecondaryInverse`.

A solution to both this checkbox 'bug' and the unothodoxy in the attributes, I propose setting the `android:theme` attribute to `@style/ThemeOverlay.AppCompat.Dark` in the root `LinearLayout`. Then the checkbox will be themed according to the theme (dark theme -> light checkbox), and all other attributes can be referenced without the `Inverse` suffix.

**Comment by mDroidd** [comment]
#7 should show a start. I didn't compile the project but perhaps it's working already.

**Comment by mlagerberg** [comment]
Indeed the Snackbar did not correctly handle a dark theme and would only show correctly if the enclosing activity had a light theme. Your pull request fixes the issue, I will merge it. Thanks!

**Comment by mDroidd** [comment]
Sorry to bother you here, but is there any way I can download the 1.1.5 version? With the `compile 'com.pixplicity.generate:library:1.+'` code I can't seem to find the merges of #2  and #7, eventhough 1.1.5 is published after that. When manually changing to `compile 'com.pixplicity.generate:library:1.1.5'` gradle gives me a "Failed to resolve" error.

**Comment by mlagerberg** [comment]
No problem! Seems like our upload to Bintray has gotten a little fucky. While we try to fix it, you can download 1.1.5 manually [here](https://bintray.com/pixplicity/android/gene-rate/1.1.5).

**Comment by mDroidd** [comment]
Thanks again!

**Comment by mlagerberg** [comment]
The issue is resolved! Had to bump version numbers for it, so you can now use Gene-rate using `compile 'com.pixplicity.generate:library:1.1.6'`.
