### ISSUE TITLE
Add cancel and rate listeners

### ISSUE THREAD

**Issue by soenkegissel** [Pixplicity/gene-rate#8]
Hi,
nice project so far. 
Could you please add more listeners to track the user or react to their choice in the dialog?
For me this is vital to see the users decision in the dialog.

**Comment by mlagerberg** [comment]
Sounds good, I'll add this in the next update

**Comment by soenkegissel** [comment]
Fantastic.

**Comment by mlagerberg** [comment]
Added in release 1.1.9.

**Comment by soenkegissel** [comment]
Wonderful! Will add this library to my projects now.
